title: My Awesome Site
description: A brief description of my site
baseurl: ""
url: "https://timaroblox5.github.io/bot-discord-test/" # ваш URL

theme: jekyll-theme-primer
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sass-converter
